### ISSUE TITLE
Disabling portmapper does not work

### ISSUE THREAD

**Issue by monotek** [bodgit/puppet-portmap#1]
I just wanted to try disabling rpcbind using your puppet module.

```
  class { '::portmap':
    manage_package => false,
  }
```
I had disabled rpcbind by hand before using the module via:
* systemctl stop rpcbind.service rpcbind.socket;systemctl disable rpcbind.service rpcbind.socket;systemctl mask rpcbind.service rpcbind.socket

When running puppet agent i get:

> 
> Error: Systemd start for rpcbind failed!
> journalctl log for rpcbind:
> -- No entries --
> 
> Error: /Stage[main]/Portmap::Service/Service[rpcbind]/ensure: change from stopped to running failed: Systemd start for rpcbind failed!
> journalctl log for rpcbind:
> -- No entries --

So it seems its only possible to start the service with your module.

Whats missing is a "manage_service" var which is able to disable portmapper service completely and therefore closes port 111.

Pull: https://github.com/bodgit/puppet-portmap/pulls

**Comment by bodgit** [comment]
I've added `service_ensure` and `service_enable` parameters. On CentOS 7.x and Ubuntu 16.04 because they use socket activation unit files (Debian 8 doesn't despite using systemd) stopping the `rpcbind.socket` unit will also stop the `rpcbind.service` unit.
